### PR TITLE
DAO

### PR DESCRIPTION
**Pull request by GordPavel**
Please test my classes for working with DB in folder src/test/java. Write all issues in comments.

### CODE REVIEW

**Comment by teomant** [comment]
1) DBScript.sql in pgAdmin/datagrip creates 12 sequences instead of 6. Specificly created sequences not used in tables.
Example:
group_id_seq - created specificly in script. Not used in tables.
group_id_seq1 - created inside table script. Used in table, where created.
2) GRANT INSERT, UPDATE, DELETE ON TABLE ufonetwork.group, message, person, person_group, planet, race TO nina; - error, unknown variable "message"

**Comment by teomant** [comment]
3. Save/Update/SaveOrUpdate of session.
Code:
         
        Session session = null;
        Transaction transaction = null;

        session = HibernateUtils.getSessionFactory().openSession();
        transaction = session.getTransaction();
        transaction.begin();

        RaceEntity raceEntity = session.get(RaceEntity.class, 1);
        if (raceEntity != null) {
        System.out.println(raceEntity.toString());
        }
        raceEntity.setName("test1");
        System.out.println(raceEntity.toString());
        session.update(raceEntity);
        session.flush();

        transaction.commit();

        RaceEntity raceEntity1 = session.get(RaceEntity.class, 1);
        System.out.println(raceEntity1.toString());

        session.close();
        HibernateUtils.shutdown();

Result:
RaceEntity(id=1, name=test, persons=[])
RaceEntity(id=1, name=test1, persons=[])
RaceEntity(id=1, name=test1, persons=[])

For real in DB nothing changes, race with id==1 still "test"

**Comment by teomant** [comment]
4. Auto-generated .toString() cause StackOverflowError
conditions:
1) 1 race, 1 person, connected to  this race.
2) person has only fields, that must be declared (id, login, pass, registration date, race), All other fileds == null
situation:
If we load race from table and try to print it, we will have StackOverflowError

Code: 

Session session = null;
 Transaction transaction = null;

 session = HibernateUtils.getSessionFactory().openSession();
 transaction = session.getTransaction();
 transaction.begin();

 RaceEntity raceEntity = session.get(RaceEntity.class, 1);
 if (raceEntity != null) {
 System.out.println(raceEntity.toString());
 }
  transaction.commit();

 session.close();
 HibernateUtils.shutdown();

**Comment by GordPavel** [comment]
1. Edited in working version, that wasn't committed.
2. Edited in working version, that wasn't committed.
4. I guess we have to make custom toString() for this classes and break this recursion there.

**Pull request merged**
